### ISSUE TITLE
heroku is shutting down their free offers

### ISSUE THREAD

**Issue by gchamon** [feedmepos/sre-take-home-assignment#1]
Came here from hackernews looking for inspiration for DevOps take home tests and came across this test.

Just wanted to point out that heroku is shutting down their free tier dynos and databases. More information here: https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

It might be of your interest to maybe remove heroku as a free offer listed in the exercise.

**Comment by pokgak** [comment]
thanks!
